### ISSUE TITLE
TokenError in Google oauth2

### ISSUE THREAD

**Issue by sarankup** [jaredhanson/passport-google-oauth#76]
Hi,

I am using passport in total.js application in which all other oath works well including facebook, twitter. But when I try to login using Google account, I got "TokenError" as error.

Please advise how to solve.

**Comment by alexkahn** [comment]
Same here. Google Console settings are correct, works in Production but not in development.

**Comment by jaredhanson** [comment]
Please provide more details.  Error messages and stack traces are helpful when debugging issues.

**Comment by alexkahn** [comment]
Sorry, just realized that:

```
500 TokenError at Strategy.OAuth2Strategy.parseErrorResponse (app/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:298:12) 
    at Strategy.OAuth2Strategy._createOAuthError (app/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:345:16) 
    at app/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:171:43 
    at app/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18 
    at passBackControl (app/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9) 
    at IncomingMessage.<anonymous> (app/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7) 
    at IncomingMessage.emit (events.js:129:20) 
    at _stream_readable.js:908:16 
    at process._tickCallback (node.js:355:11)
```

**Comment by sarankup** [comment]
Hi, 

For me, the google sign in page, opens and I click the account and then "Accept", again the page redirect to google login over and over again. Here goes the error message in console.

createCredentials() is deprecated, use tls.createSecureContext instead
error happenTokenError

**Comment by aendrew** [comment]
I'm using this with generator-angular-fullstack and am getting the "createCredentials is depreciated" error as well:

```GET /auth/google 302 3ms - 0b
createCredentials() is deprecated, use tls.createSecureContext instead
InternalOAuthError: failed to fetch user profile
    at /Users/arininsland/Sites/st_covers/backend/node_modules/passport-google-oauth/lib/passport-google-oauth/oauth2.js:88:28
    at passBackControl (/Users/arininsland/Sites/st_covers/backend/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9)
    at IncomingMessage.<anonymous> (/Users/arininsland/Sites/st_covers/backend/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
GET /auth/google/callback?code=[obfuscated] 500 861ms - 718b
```

**Comment by alexkahn** [comment]
Just a note: my problem was solved.

Solution:
I was using the same API credentials in both development and staging so Google wouldn't let me create a sign in on the same app (in it's eyes) from two locations.

**Comment by sarankup** [comment]
Hi, Any update on this. It seems my problem is not resolved.

**Comment by sarankup** [comment]
Does that mean, you want me to create a new app key in Google and assign?

In my case, I am just in the localhost, and not to place hosting now.

**Comment by aendrew** [comment]
@sarankup If you already have a project in the API console you're using, go to https://console.developers.google.com, click "APIs & auth", "APIs", "Google+ API", "Enable API". Otherwise create a new project and do that.

**Comment by adamk33n3r** [comment]
@aendrew Thanks you saved me a bunch of headache. I didn't even think of doing that.

**Comment by amejiarosario** [comment]
For anybody strugguling with it...

1. You need to go API & auth > APIs and enable Google+ API. 
2. Later click on Explore this API and enable Authorize requests using OAuth 2.0 as shown
![image](https://cloud.githubusercontent.com/assets/418605/9242408/c06f6b66-414e-11e5-834c-c8e813d00737.png)


3. Furthermore, you need to go API & auth > APIs and enable Google+ API. Later click on Explore this API and enable Authorize requests using OAuth 2.0.

![image](https://cloud.githubusercontent.com/assets/418605/9242402/b788b2be-414e-11e5-9e7c-bd7cc0dad017.png)

**Comment by si74** [comment]
@alexkahn Could you elaborate a bit on how you solved this problem? Having a similar issue and I've tried all of the aforementioned steps but alas - no cigar.

**Comment by imdadul** [comment]
@amejiarosario Thanks. But that's not working for me.
Once I select & authorize , it shows 'ON' in top right, then I refresh, it shows OFF again. Am I missing anything ?

**Comment by OttlikG** [comment]
Same problem here. When I switch On it immediately turn Off after page refresh.

**Comment by imdadul** [comment]
@OttlikG . What I found that it actually does not matter, if you turned on, you can be sure that it actually turned on. So that worked for me.
And make sure that, your keys are trimmed (no space) when added into the code.

**Comment by OttlikG** [comment]
@imdadul Thanks, I came to the same solution one day ago.

**Comment by sunitJindal** [comment]
It seems to be an issue with Google it self. Am also facing the issue, every time i turn on the "Authorize requests using OAuth 2.0:" option and i refresh the page it's turned off every time... I am pretty sure as when this stupid thing is turned on, Passport would work just fine

**Comment by divneet** [comment]
hey ,  i'm facing a similar problem and can not solve ot using the given solutions . let me know what changes i can make to debug the code

**Comment by divneet** [comment]
@aendrew  hey , do you have idea what i am doing wrong here . 
at Strategy.OAuth2Strategy.parseErrorResponse (/home/hadoop/Documents/jobninja/node-oauth/new-oauth/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:298:12)
at Strategy.OAuth2Strategy._createOAuthError (/home/hadoop/Documents/jobninja/node-oauth/new-oauth/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:345:16)
at /home/hadoop/Documents/jobninja/node-oauth/new-oauth/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:171:43
at /home/hadoop/Documents/jobninja/node-oauth/new-oauth/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
at passBackControl (/home/hadoop/Documents/jobninja/node-oauth/new-oauth/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
at IncomingMessage. (/home/hadoop/Documents/jobninja/node-oauth/new-oauth/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
at IncomingMessage.emit (events.js:129:20)
at _stream_readable.js:908:16
at process._tickCallback (node.js:355:11)

**Comment by divneet** [comment]
hey @alexkahn  can you help me out here ?

**Comment by alexkahn** [comment]
@divneet @si74 My issue was just having one set of credentials for an app that I had in both development and production. All I had to do was set up some API credentials for both environments. If you aren't in that scenario then I don't really know what else to tell you.

**Comment by divneet** [comment]
hey @OttlikG  can you help me out here ?

**Comment by OttlikG** [comment]
I just copied the key with an additional space and that caused the problem.
I'm afraid of that I can't help you.

**Comment by amitbhatnagar** [comment]
I get the same error when google calls my callback URL with a code

I'm using node 4.2.4 with express 4.13.3

"http:// domainname .com/login/google/callback?code=xxxxxxxxxxx"

TokenError
   at Strategy.OAuth2Strategy.parseErrorResponse (/var/app/current/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:298:12)
   at Strategy.OAuth2Strategy._createOAuthError (/var/app/current/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:345:16)
   at /var/app/current/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:171:43
   at /var/app/current/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
   at passBackControl (/var/app/current/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/var/app/current/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
   at IncomingMessage.emit (events.js:129:20)
   at _stream_readable.js:908:16
   at process._tickDomainCallback (node.js:381:11)

I have tried all the workaround mentioned in this post but still getting the same error.

**Comment by divneet** [comment]
@amitbhatnagar  try using everyauth ,since i wasn't able to work it out .

**Comment by sebnapi** [comment]
Make sure to check client-id and client-secret, wasted two hours on this, just because I assumed I did it right :expressionless:

**Comment by krishangupta** [comment]
@aendrew's solution worked for me. Thanks!

**Comment by ruichao-factual** [comment]
I meet a similar Error. The reason for my issue  is that my server can't access google. 😭

**Comment by sayingu** [comment]
In my case,
`var GoogleStrategy = require( 'passport-google-oauth2' ).Strategy;`
to
`var GoogleStarategy = require('passport-google-oauth').OAuth2Strategy;`
then it works.

**Comment by sebaveg** [comment]
I was an hour with the same error. My error was in callbackURL: 'auth/google/redirect'. The correct is callbackURL: '/auth/google/redirect'﻿

**Comment by sojelee** [comment]
Thank you guys for all you answers, just spent 4 hours trying to get the passportjs social authentication, I managed to get twitter,facebook and github authenticating, but I got stuck on google, as I was getting to the authentication page to then got some errors, until I found this page, I had not enabled Google + API, you really all served my dat

**Comment by pal-p** [comment]
I had the exact same problem when deploying to heroku. Unauthorized token error means that your client secret is not entered correctly. Make sure it doesn't contain spaces when copying

**Comment by shankywwww** [comment]
Did anyone get client_secret is missing error. 
I am passing following object for google strategy 

const GoogleStrategy = require('passport-google-oauth20').Strategy

passport.use ( new GoogleStrategy ({
    clientID: keys.googleClientID,
    clent_secret: keys.googleClientSecret,
    callbackURL: '/auth/google/callback'
}, (accessToken) => {
    console.log(accessToken)
}))

Find the error details below. 

TokenError: client_secret is missing.
    at Strategy.OAuth2Strategy.parseErrorResponse (D:\Users\shasdr\Documents\FullStack\server\node_modules\passport-oauth2\lib\strategy.js:330:12)
    at Strategy.OAuth2Strategy._createOAuthError (D:\Users\shasdr\Documents\FullStack\server\node_modules\passport-oauth2\lib\strategy.js:377:16)
    at D:\Users\shasdr\Documents\FullStack\server\node_modules\passport-oauth2\lib\strategy.js:166:45
    at D:\Users\shasdr\Documents\FullStack\server\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (D:\Users\shasdr\Documents\FullStack\server\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (D:\Users\shasdr\Documents\FullStack\server\node_modules\oauth\lib\oauth2.js:157:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)

unable to find fix. tried all the suggestions given in the above comment thread.

**Comment by leonardfactory** [comment]
> passport.use ( new GoogleStrategy ({
> clientID: keys.googleClientID,
> clent_secret: keys.googleClientSecret,
> callbackURL: '/auth/google/callback'
> }, (accessToken) => {
> console.log(accessToken)
> }))
> 

@shankywwww Not sure if you already solved this, however, It seems you're using `client_secret` but it should be `clientSecret`

**Comment by kirillzhurin** [comment]
@SambhavS004 if you use _**scope: ['profile', 'email']**_ maybe issue in the scope, try to change scope like so _**scope: ['https://www.googleapis.com/auth/plus.login']**_

**Comment by clearloop** [comment]
check the typo of secretKey and clientKey....That's what controlled my google+ API...

**Comment by dimasi** [comment]
In my case:

```
passport.use(new GoogleStrategy({
    clientID: config.google[env].appId,
    clientSecret: config.google[env].clientSecret, // <- console.log(config.google[env].clientSecret === undefined)
    callbackURL: `${(options.baseUrl || '')}/auth/google/callback`,
    passReqToCallback: true,
}, (request, accessToken, refreshToken, profile, done) => { ... }));

```
Just a typo. Instead of **config.google[env].clientSecret** should have been **config.google[env].appSecret**

**Comment by naveenk2k** [comment]
> I am also getting the same error, have tried almost every suggestion present here, but none of them worked. Kindly help.
> 
> TokenError: Bad Request
> at Strategy.OAuth2Strategy.parseErrorResponse (F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\passport-oauth2\lib\strategy.js:329:12)
> at Strategy.OAuth2Strategy._createOAuthError (F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\passport-oauth2\lib\strategy.js:376:16)
> at F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\passport-oauth2\lib\strategy.js:166:45
> at F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\oauth\lib\oauth2.js:191:18
> at passBackControl (F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\oauth\lib\oauth2.js:132:9)
> at IncomingMessage. (F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\oauth\lib\oauth2.js:157:7)
> at emitNone (events.js:111:20)
> at IncomingMessage.emit (events.js:208:7)
> at endReadableNT (_stream_readable.js:1064:12)
> at _combinedTickCallback (internal/process/next_tick.js:138:11)

@SambhavS004 I'm getting the exact same error. Did you manage to fix it?

**Comment by Hameed098** [comment]
is there any single man to fix this error?

**Comment by Kumarsuman21** [comment]
> > I am also getting the same error, have tried almost every suggestion present here, but none of them worked. Kindly help.
> > TokenError: Bad Request
> > at Strategy.OAuth2Strategy.parseErrorResponse (F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\passport-oauth2\lib\strategy.js:329:12)
> > at Strategy.OAuth2Strategy._createOAuthError (F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\passport-oauth2\lib\strategy.js:376:16)
> > at F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\passport-oauth2\lib\strategy.js:166:45
> > at F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\oauth\lib\oauth2.js:191:18
> > at passBackControl (F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\oauth\lib\oauth2.js:132:9)
> > at IncomingMessage. (F:\Sambhav\Nodejs_Practice\Udemy\Node_React\node_modules\oauth\lib\oauth2.js:157:7)
> > at emitNone (events.js:111:20)
> > at IncomingMessage.emit (events.js:208:7)
> > at endReadableNT (_stream_readable.js:1064:12)
> > at _combinedTickCallback (internal/process/next_tick.js:138:11)
> 
> @SambhavS004 I'm getting the exact same error. Did you manage to fix it?

In my case, I deleted the old credentials and created new one in the same google api project. I went to this https://console.developers.google.com/apis/credentials, selected the project, deleted the existed one OAuth 2.0 client ID and created new credentials with OAuth client ID then used the new clientID & clientSecret in my code. This is working fine for me.

**Comment by vikjdk7** [comment]
I also encountered same issue while trying to invoke callback function,

_**TokenError: Bad Request
    at Strategy.OAuth2Strategy.parseErrorResponse (/Users/C5272869/Documents/node js/The Net Ninja/passportjs project/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/Users/C5272869/Documents/node js/The Net Ninja/passportjs project/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /Users/C5272869/Documents/node js/The Net Ninja/passportjs project/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /Users/C5272869/Documents/node js/The Net Ninja/passportjs project/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/Users/C5272869/Documents/node js/The Net Ninja/passportjs project/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/C5272869/Documents/node js/The Net Ninja/passportjs project/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)**_

Solution - Two solutions I found feasible which worked for me
a. ```
passport.use(new GoogleStrategy({
    //options for google strategy
    callbackURL: '**/auth/google/redirect'**, //I forgot initial / before auth.
    clientID: keys.google.clientID,
    clientSecret: keys.google.clientSecret
}, (accessToken, refreshToken, profile, done) => {
    //passport callback function
    console.log('--------- callback function fired ---------');
    console.log(profile);

}))
```
b. credentials should be used wisely on different deployment platforms.

**Comment by JayGondalia** [comment]
TokenError: Bad Request
    at Strategy.OAuth2Strategy.parseErrorResponse (f:\Angular\node\oauth\node_modules\passport-oauth2\lib\strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (f:\Angular\node\oauth\node_modules\passport-oauth2\lib\strategy.js:405:16)
    at f:\Angular\node\oauth\node_modules\passport-oauth2\lib\strategy.js:175:45
    at f:\Angular\node\oauth\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (f:\Angular\node\oauth\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (f:\Angular\node\oauth\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
TokenError: Bad Request
    at Strategy.OAuth2Strategy.parseErrorResponse (f:\Angular\node\oauth\node_modules\passport-oauth2\lib\strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (f:\Angular\node\oauth\node_modules\passport-oauth2\lib\strategy.js:405:16)
    at f:\Angular\node\oauth\node_modules\passport-oauth2\lib\strategy.js:175:45
    at f:\Angular\node\oauth\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (f:\Angular\node\oauth\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (f:\Angular\node\oauth\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

 can anyone help me how to solve >?

**Comment by brookmg** [comment]
This issue seems to be active since 2015. Any other strategy you guys started using instead of this for OAuth2 with google?

**Comment by brookmg** [comment]
I found out that this way caused because of some kind of `timeout` error for me. Mainly because I didn't call the done callback function passed from the strategy. 

```ts
Passport.use(new GoogleStrategy({
        clientID: '',   // 266033008053-06q(MORE).apps.googleusercontent.com
        clientSecret: '', // eEriCU9KEX(MORE)
        callbackURL: "http://localhost:3400/auth/google/callback"
    }, (accessToken , refreshToken, profile, done) => {
        console.log(`${accessToken} -> access token`);
        console.log(`${refreshToken} -> refresh token`);

        // Store user's token in the db but with more security.
        done(false, {strategy: 'google' , accessToken , refreshToken , ...profile});
    })
);
```
* don't forget to defined the `Passport.serializeUser` and `Passport.deserializeUser` functions also

**Comment by tesla809** [comment]
resetting the credentials like @sumanmahto mentioned worked for me.

**Comment by hfuentes** [comment]
Catch all errors...
```
exports.setup = () => {
    passport.use(new GoogleStrategy({
        clientID: config.client_id,
        clientSecret: config.client_secret,
        callbackURL: config.callback_uri
    }, (accessToken, refreshToken, profile, done) => {
        if (profile && profile._json && profile._json.email) {
            return User.findOne({ email: profile._json.email }).exec().then(user => {
                user.displayName = profile._json.name
                user.photoURL = profile._json.picture
                return user.save()
            }).then(savedUser => done(null, savedUser)).catch(done)
        } else return done()
    }))
}
```

**Comment by vishwa3** [comment]
I am also getting the same error 
`TokenError: Bad Request`
Please let me know if google sign in can be implemented without using passport

**Comment by wenqiuZhou** [comment]
I encountered the same problem because I removed   "return cb(err, user);" 
code as below works well: findOrCreate is from "mongoose-findorcreate"

passport.use(new GoogleStrategy({
    clientID: process.env.ClientID,
    clientSecret: process.env.ClientKey,
    callbackURL: "xxxx"
    userProfileURL: "https://www.googleapis.com/oauth2/v3/userinfo"
  },
  function(accessToken, refreshToken, profile, cb) {
    User.findOrCreate({
      googleId: profile.id
    }, function(err, user) {
      return cb(err, user);
;
    });
  }
));

**Comment by Karishmasahoo99** [comment]
For me, when we access googleId from mongodb it found to be undefined . Instead of writing googleId we can write

User.findOne({"req.user.googleId":profile.id}){
.....
}
My error is solved in this way

**Comment by RanjeetSingh00** [comment]
Hey Guys! This Error have Best Solution:

Replace Following Code:

passport.use(new GoogleStrategy({
                clientID: process.env.GOOGLE_CLIENT_ID,
                clientSecret: process.env.GOOGLE_CLIENT_SECRET,
                callbackURL: '/auth/google/callback'
            },
            async (accessToken, refreshToken, profile, done) => {
                // Users full Profile by Google
                // console.log(profile)
                const newUser = {
                    googleId: profile.id,
                    displayName: profile.displayName,
                    firstName: profile.name.givenName,
                    lastName: profile.name.familyName,
                    image: profile.photos[0].value
                }
             
               console.log(newUser)
               // you forgot this
              done(null, null)

**Comment by Cupruminvictus** [comment]
hi

**Comment by EfiGordon** [comment]
For me the solution was a missing slash in the 

```
passport.use(new GoogleStrategy({
    clientID: keys.GOOGLE_CLIENT_ID,
    clientSecret: keys.GOOGLE_CLIENT_SECRET,
    callbackURL: "/auth/google/callback",
    proxy: true
},
```

instead of `callbackURL: "/auth/google/callback"` it was `callbackURL: "auth/google/callback"`

**Comment by LuckeeDev** [comment]
April 2021 and having this exact issue, any idea on how to solve this? It works fine in development but in production it starts throwing errors.

**Comment by buckwilson** [comment]
I was pulling my hair out trying to figure this one out - turns out it was Safari trying to autocomplete my URL to the callback and hitting the server trying to fetch the title. 

<img width="551" alt="CleanShot 2021-04-20 at 09 33 52@2x" src="https://user-images.githubusercontent.com/31074/115414331-8c50e480-a1bb-11eb-83d9-f659e2702d0a.png">


Don't know if that helps anyone else or if I'm the only bonehead but I thought I'd share.

**Comment by LuckeeDev** [comment]
@buckwilson interesting, my issue is that it's only happening in production... do you think that someone with Safari on their device might be getting a wrong autocomplete url?

**Comment by abubakarMana01** [comment]
"app.use(passport.initialize())" in the root file in my case "server.js" fixed TokenError:BadRequest for me.

**Comment by BartDrown** [comment]
> Make sure to check client-id and client-secret, wasted two hours on this, just because I assumed I did it right expressionless

As funny and as dumb it must sound, it was the issue in my case. Got typo in passed parameter type, even though env was passed. Thanks for that comment as it encouraged me to review it more closely and find the actual issue

**Comment by ELIJAHKUNGU** [comment]
> 

const GoogleStrategy = require('passport-google-oauth20').Strategy
// const mongoose = require('mongoose')
const User = require('../models/Users')

module.exports = function(passport) {
    passport.use(
        new GoogleStrategy({
                clientID: process.env.GOOGLE_CLIENT_ID,
                clientSecret: process.env.GOOGLE_CLIENT_SECRET,
                callbackURL: 'http://localhost:3000/auth/google/callback'
            },
            async(accessToken, refreshToken, profile, done) => {
                const newUser = {
                    googleId: profile.id,
                    displayName: profile.displayName,
                    firstName: profile.name.givenName,
                    lastName: profile.name.familyName,
                    image: profile.photos[0].value,
                }

                try {
                    let user = await User.findOne({ googleId: profile.id })

                    if (user) {
                        done(null, user)
                    } else {
                        user = await User.create(newUser)
                        done(null, user)
                    }
                } catch (err) {
                    console.error(err)
                }
                // console.log(profile);
            }
        )
    )

    passport.serializeUser((user, done) => {
        done(null, user.id)
    })

    passport.deserializeUser((id, done) => {
        User.findById(id, (err, user) => done(err, user))
    })
}

**Comment by acchang** [comment]
thank you for having this thread available! I couldn't figure out why I was getting "TokenError: client_secret is missing." until I tried almost everything. Then I saw: It was a typo!!

module.exports = function(passport) {
    passport.use(new GoogleStrategy({
        clientID: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOLE_CLIENT_SECRET,
        callbackURL: '/auth/google/callback'

Now I'm getting "InternalOAuthError: Failed to fetch user profile"

**Comment by ELIJAHKUNGU** [comment]
You're welcome

Happy hacking

**Comment by pkjagesia** [comment]
If someone is still stuck with the `TokenError : Bad Request` error and are using the `successReturnToOrRedirect` parameter in the callback route, try changing it to `successRedirect`. That's what finally worked for me after spending almost an entire day on it :/

**Comment by 7saikat7** [comment]
In 2023 I am getting the same error, :) . I have checked all of the cases in my knowledge but didn't find any solution.
What could possibly go wrong??

**Comment by 7saikat7** [comment]
finally something worked !! 
```
app.get('/auth/google/callback',
  passport.authenticate('google'), // complete the authenticate using the google strategy
  (err, req, res, next) => { // custom error handler to catch any errors, such as TokenError
    if (err.name === 'TokenError') {
     res.redirect('/auth/google'); // redirect them back to the login page
    } else {
     // Handle other errors here
    }
  },
  (req, res) => { // On success, redirect back to '/'
    res.redirect('/');
  }
);
``

**Comment by JeherillaJanwar** [comment]
After 8 years, I'm still getting this stupid error:

```bash
TokenError: Bad Request
    at OAuth2Strategy.parseErrorResponse (/home/ishaan/Project_NAME/node_modules/passport-oauth2/lib/strategy.js:373:12)
    at OAuth2Strategy._createOAuthError (/home/ishaan/Project_NAME/node_modules/passport-oauth2/lib/strategy.js:420:16)
    at /home/ishaan/Project_NAME/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /home/ishaan/Project_NAME/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/ishaan/Project_NAME/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/ishaan/Project_NAME/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
I have tried almost all of the suggestions listed by others, but nothing seems to work.

PS: I'm not experiencing this error in Incognito Mode (Private Browsing)... I am starting to think if this is only a Chrome non-incognito error. Thus, I cleared the cache and browsing data, but it still isn't working.

Does anyone here know how to fix this error?

**Comment by JeherillaJanwar** [comment]
After 8 years, I'm still getting this  error:
```bash
TokenError: Bad Request
    at OAuth2Strategy.parseErrorResponse (/home/ishaan/Project_NAME/node_modules/passport-oauth2/lib/strategy.js:373:12)
    at OAuth2Strategy._createOAuthError (/home/ishaan/Project_NAME/node_modules/passport-oauth2/lib/strategy.js:420:16)
    at /home/ishaan/Project_NAME/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /home/ishaan/Project_NAME/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/ishaan/Project_NAME/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/ishaan/Project_NAME/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I have tried almost all of the suggestions listed by others, but nothing seems to work.

PS: I'm not experiencing this error in Incognito Mode (Private Browsing)... I am starting to think if this is only a Chrome non-incognito error. Thus, I cleared the cache and browsing data, but it still isn't working.

Does anyone here know how to fix this error?

**Comment by SerhiiZimovets** [comment]
i have this error (TokenError: Bad Request) on prod, but not always just sometimes we catch it, and i wondering what the reason, my investigation result is that inside passport logic we make request to google to try get token and get broken response, finally i could reproduce the error ,  during google log in login front send request to back like this (http://localhost:3000/auth/google/redirect?code=4%2F0Ad.... bla...bla...bla) the key is the code parameter, so if we try to make the request second time with the same code we get the error, i suppose because we already use code to authorize user, but main question WHY AND HOW it happens on front-end, why we make this request second time it is mystery for me, and additionally i reproduce the error accidentally, i found url in chrome history it was yesterday but today the url is gone) cant find it, some thoughts??? 
![image](https://github.com/jaredhanson/passport-google-oauth/assets/132881036/fd940aff-f0b8-4efe-a5d3-090bd47c8f6a)

**Comment by Cavein254** [comment]
The problem was the urls
```js
app.get(
  "/auth/google",
  passport.authenticate("google", { scope: ["profile", "email"] })
);

app.get(
  "/auth/google/callback",
  passport.authenticate("google", { failureRedirect: "/login" }),
  async (req, res) => {
    res.redirect("/");
  }
);
```
